/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import beans.AnimalBean;
import beans.ClienteBean;
import beans.EnderecoBean;
import controllers.AnimalController;
import controllers.ClienteController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import utils.Dataconverter;

/**
 *
 * @author cacai
 */
public class AnimalDetalhes extends javax.swing.JFrame {

    AnimalBean ab;
    AnimalController ac;

    public AnimalDetalhes() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        ab = new AnimalBean();
        ac = new AnimalController(ab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelanimal = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nomeanimaltxt = new javax.swing.JTextField();
        pesoanimaltxt = new javax.swing.JTextField();
        racatxt = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        concluirbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        close3 = new javax.swing.JPanel();
        closelabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idtxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelanimal.setBackground(new java.awt.Color(255, 255, 255));
        panelanimal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel13.setText("Alterar animal");
        panelanimal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel14.setText("Nome");
        panelanimal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel15.setText("Peso");
        panelanimal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel16.setText("Raça");
        panelanimal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        nomeanimaltxt.setBorder(null);
        panelanimal.add(nomeanimaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 160, -1));

        pesoanimaltxt.setBorder(null);
        panelanimal.add(pesoanimaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 190, -1));

        racatxt.setBorder(null);
        panelanimal.add(racatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 190, -1));
        panelanimal.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));
        panelanimal.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 160, 10));
        panelanimal.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 190, 10));
        panelanimal.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 190, 10));

        concluirbtn.setBackground(new java.awt.Color(255, 255, 255));
        concluirbtn.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        concluirbtn.setText("Alterar");
        concluirbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        concluirbtn.setContentAreaFilled(false);
        concluirbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        concluirbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                concluirbtnMouseClicked(evt);
            }
        });
        panelanimal.add(concluirbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 110, 35));

        cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelbtn.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        cancelbtn.setText("Cancelar");
        cancelbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        cancelbtn.setContentAreaFilled(false);
        cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelanimal.add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 110, 35));
        panelanimal.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 160, 10));

        jLabel19.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel19.setText("Nome");
        panelanimal.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/alteraranimal.png"))); // NOI18N
        panelanimal.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 190, 480));

        close3.setBackground(new java.awt.Color(255, 101, 101));
        close3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close3MouseExited(evt);
            }
        });
        close3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closelabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        closelabel3.setForeground(new java.awt.Color(255, 255, 255));
        closelabel3.setText("X");
        close3.add(closelabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        panelanimal.add(close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/eraser.png"))); // NOI18N
        jLabel2.setText("Excluir");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panelanimal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        idtxt.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        idtxt.setForeground(new java.awt.Color(153, 204, 255));
        idtxt.setText("jLabel1");
        panelanimal.add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 50, 20));

        getContentPane().add(panelanimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void concluirbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_concluirbtnMouseClicked
        // TODO add your handling code here:

        ab.setNome(nomeanimaltxt.getText());
        ab.setPeso(Double.parseDouble(pesoanimaltxt.getText()));
        ab.setRaca(racatxt.getText());

        this.ac.alterar();

    }//GEN-LAST:event_concluirbtnMouseClicked

    public void receberDados(String id, String nome, String peso, String raca) {

        idtxt.setText("ID: " + id);
        nomeanimaltxt.setText(nome);
        pesoanimaltxt.setText(peso);
        racatxt.setText(raca);

    }

    private void close3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseClicked
        try {
            Pets home = new Pets();
            this.setVisible(false);
            home.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AnimalDetalhes.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_close3MouseClicked

    private void close3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseEntered

        Color darkred = new Color(130, 0, 0);

        close3.setBackground(darkred);
    }//GEN-LAST:event_close3MouseEntered

    private void close3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseExited
        Color red = new Color(255, 101, 101);

        close3.setBackground(red);
        closelabel3.setForeground(Color.WHITE);
    }//GEN-LAST:event_close3MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        ab.setIdAnimal(Integer.parseInt(idtxt.getText()));
        this.ac.remover();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalDetalhes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JPanel close3;
    private javax.swing.JLabel closelabel3;
    private javax.swing.JButton concluirbtn;
    private javax.swing.JLabel idtxt;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JTextField nomeanimaltxt;
    private javax.swing.JPanel panelanimal;
    private javax.swing.JTextField pesoanimaltxt;
    private javax.swing.JTextField racatxt;
    // End of variables declaration//GEN-END:variables
}
