/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import View.Home;
import beans.ServicoBean;
import controllers.ItemController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author cacai
 */
public class Cadastro_servico extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_servico
     */
    ServicoBean sb= null;
    ItemController ic = null;
    public Cadastro_servico() {
        initComponents();
        this.sb = new ServicoBean();
        this.ic = new ItemController(null, sb);
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

    }
    public  void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon_1.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelservico = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nomeservico = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        concluirbtn2 = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaotxt = new javax.swing.JTextArea();
        close3 = new javax.swing.JPanel();
        closelabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelservico.setBackground(new java.awt.Color(255, 255, 255));
        panelservico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel19.setText("Cadastre um serviço");
        panelservico.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel20.setText("Nome");
        panelservico.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel21.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel21.setText("Valor");
        panelservico.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        nomeservico.setBorder(null);
        panelservico.add(nomeservico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 160, -1));

        valor.setBorder(null);
        panelservico.add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 190, -1));
        panelservico.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));
        panelservico.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 160, 10));
        panelservico.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 190, 10));

        concluirbtn2.setBackground(new java.awt.Color(255, 255, 255));
        concluirbtn2.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        concluirbtn2.setText("Concluir");
        concluirbtn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        concluirbtn2.setContentAreaFilled(false);
        concluirbtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        concluirbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                concluirbtn2MouseClicked(evt);
            }
        });
        panelservico.add(concluirbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 110, 35));

        cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelbtn.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        cancelbtn.setText("Cancelar");
        cancelbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        cancelbtn.setContentAreaFilled(false);
        cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelservico.add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 110, 35));
        panelservico.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 160, 10));

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel22.setText("Nome");
        panelservico.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/servicos.png"))); // NOI18N
        panelservico.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 190, 480));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descriçao", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        descricaotxt.setColumns(20);
        descricaotxt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        descricaotxt.setLineWrap(true);
        descricaotxt.setRows(5);
        jScrollPane1.setViewportView(descricaotxt);

        panelservico.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 230, 200));

        close3.setBackground(new java.awt.Color(255, 101, 101));
        close3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close3MouseExited(evt);
            }
        });
        close3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closelabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        closelabel3.setForeground(new java.awt.Color(255, 255, 255));
        closelabel3.setText("X");
        close3.add(closelabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        panelservico.add(close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 40, 30));

        getContentPane().add(panelservico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 657, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void concluirbtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_concluirbtn2MouseClicked

       
 
        this.sb.setNome(nomeservico.getText());
        this.sb.setValor(Double.parseDouble(valor.getText()));
        this.sb.setDescricao(descricaotxt.getText());
        this.ic.cadastrarServico();

    }//GEN-LAST:event_concluirbtn2MouseClicked

    private void close3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseClicked
        Home home = new Home();
        this.setVisible(false);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_close3MouseClicked

    private void close3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseEntered

        Color darkred = new Color(130, 0, 0);

        close3.setBackground(darkred);
    }//GEN-LAST:event_close3MouseEntered

    private void close3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseExited
        Color red = new Color(255, 101, 101);

        close3.setBackground(red);
        closelabel3.setForeground(Color.WHITE);
    }//GEN-LAST:event_close3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_servico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JPanel close3;
    private javax.swing.JLabel closelabel3;
    private javax.swing.JButton concluirbtn2;
    private javax.swing.JTextArea descricaotxt;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JTextField nomeservico;
    private javax.swing.JPanel panelservico;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
