/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import beans.ProdutoBean;
import controllers.ItemController;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.etec
 */
public class Cadastro_produto extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_cliente
     */
    ProdutoBean pb;
    ItemController ic;

    public Cadastro_produto() {
        pb = new ProdutoBean();
        ic = new ItemController(pb, null);

        setIcon();
        initComponents();
    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon_1.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelproduto = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nomeptxt = new javax.swing.JTextField();
        valortxt = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        concluirbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        categorias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaotxt = new javax.swing.JTextArea();
        close3 = new javax.swing.JPanel();
        closelabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelproduto.setBackground(new java.awt.Color(255, 255, 255));
        panelproduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel13.setText("Cadastre um produto");
        panelproduto.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel14.setText("Nome");
        panelproduto.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel15.setText("Valor");
        panelproduto.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        nomeptxt.setBorder(null);
        panelproduto.add(nomeptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 160, -1));

        valortxt.setBorder(null);
        panelproduto.add(valortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 190, -1));
        panelproduto.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));
        panelproduto.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 160, 10));
        panelproduto.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 190, 10));

        concluirbtn.setBackground(new java.awt.Color(255, 255, 255));
        concluirbtn.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        concluirbtn.setText("Concluir");
        concluirbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        concluirbtn.setContentAreaFilled(false);
        concluirbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        concluirbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                concluirbtnMouseClicked(evt);
            }
        });
        concluirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirbtnActionPerformed(evt);
            }
        });
        panelproduto.add(concluirbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 110, 35));

        cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelbtn.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        cancelbtn.setText("Cancelar");
        cancelbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        cancelbtn.setContentAreaFilled(false);
        cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelproduto.add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 110, 35));
        panelproduto.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 160, 10));

        jLabel19.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel19.setText("Nome");
        panelproduto.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/produtos.png"))); // NOI18N
        panelproduto.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 190, 480));

        categorias.setForeground(new java.awt.Color(51, 102, 255));
        categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a categoria", "Brinquedo", "Acessório", "Medicação" }));
        categorias.setBorder(null);
        panelproduto.add(categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 90, 140, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descriçao", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        descricaotxt.setColumns(20);
        descricaotxt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        descricaotxt.setLineWrap(true);
        descricaotxt.setRows(5);
        jScrollPane1.setViewportView(descricaotxt);

        panelproduto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 230, 200));

        close3.setBackground(new java.awt.Color(255, 101, 101));
        close3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close3MouseExited(evt);
            }
        });
        close3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closelabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        closelabel3.setForeground(new java.awt.Color(255, 255, 255));
        closelabel3.setText("X");
        close3.add(closelabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        panelproduto.add(close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 40, 30));

        getContentPane().add(panelproduto, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void concluirbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_concluirbtnMouseClicked

        int select = categorias.getSelectedIndex();
        switch (select) {

            case 0:
                JOptionPane.showMessageDialog(null, "Selecione a categoria do produto");
                break;
            case 1:
                this.pb.setCategoria("Brinquedo");
                break;

            case 2:
                this.pb.setCategoria("Acessório");
                break;

            case 3:
                this.pb.setCategoria("Medicaçao");
                break;

        }

        System.out.println(this.pb.getCategoria());

        this.pb.setNome(nomeptxt.getText());
        this.pb.setValor(Double.parseDouble(valortxt.getText()));
        this.pb.setDescricao(descricaotxt.getText());
        this.ic.cadastrarItem();


    }//GEN-LAST:event_concluirbtnMouseClicked

    private void close3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseClicked
        voltar();
    }//GEN-LAST:event_close3MouseClicked

    private void close3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseEntered

        Color darkred = new Color(130, 0, 0);

        close3.setBackground(darkred);
    }//GEN-LAST:event_close3MouseEntered

    private void close3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseExited
        Color red = new Color(255, 101, 101);

        close3.setBackground(red);
        closelabel3.setForeground(Color.WHITE);
    }//GEN-LAST:event_close3MouseExited

    private void concluirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concluirbtnActionPerformed

    private void voltar() {
        View.Home home = new View.Home();
        this.setVisible(false);
        home.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JComboBox<String> categorias;
    private javax.swing.JPanel close3;
    private javax.swing.JLabel closelabel3;
    private javax.swing.JButton concluirbtn;
    private javax.swing.JTextArea descricaotxt;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JTextField nomeptxt;
    private javax.swing.JPanel panelproduto;
    private javax.swing.JTextField valortxt;
    // End of variables declaration//GEN-END:variables
}
