/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import view.Cadastro_produto;
import view.Cadastro_servico;

/**
 *
 * @author cacai
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Color hover = new Color(224, 224, 224);
    Color base = new Color(247, 249, 249);

    public Home() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        setIcon();

    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon_1.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        closelabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        funcionariobtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        petlistbtn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        listaclientebtn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        servicolist = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        produtobtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cadastrarbtn1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        funcionariolist1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        produtolist = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        servicobtn1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/home.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("IPet");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gerenciador de Petshop");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        close.setBackground(new java.awt.Color(255, 101, 101));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closelabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        closelabel.setForeground(new java.awt.Color(255, 255, 255));
        closelabel.setText("X");
        close.add(closelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        funcionariobtn.setBackground(new java.awt.Color(247, 249, 249));
        funcionariobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        funcionariobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funcionariobtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                funcionariobtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                funcionariobtnMouseExited(evt);
            }
        });
        funcionariobtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 255));
        jLabel11.setText("Cadastrar funcionário");
        funcionariobtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/id-badge.png"))); // NOI18N
        funcionariobtn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel2.add(funcionariobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 130, 130));

        petlistbtn.setBackground(new java.awt.Color(247, 249, 249));
        petlistbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        petlistbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petlistbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                petlistbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                petlistbtnMouseExited(evt);
            }
        });
        petlistbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("Pets cadastrados");
        petlistbtn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/pets.png"))); // NOI18N
        petlistbtn.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel2.add(petlistbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 120, 120));

        listaclientebtn.setBackground(new java.awt.Color(247, 249, 249));
        listaclientebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listaclientebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaclientebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listaclientebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listaclientebtnMouseExited(evt);
            }
        });
        listaclientebtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Clientes cadastrados");
        listaclientebtn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cliente.png"))); // NOI18N
        listaclientebtn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel2.add(listaclientebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 130, 120));

        servicolist.setBackground(new java.awt.Color(247, 249, 249));
        servicolist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        servicolist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicolistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                servicolistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                servicolistMouseExited(evt);
            }
        });
        servicolist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 153, 255));
        jLabel14.setText("Serviços cadastrados");
        servicolist.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/grooming.png"))); // NOI18N
        servicolist.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel2.add(servicolist, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 130, 120));

        produtobtn.setBackground(new java.awt.Color(247, 249, 249));
        produtobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        produtobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtobtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                produtobtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                produtobtnMouseExited(evt);
            }
        });
        produtobtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Cadastrar Produto");
        produtobtn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ball.png"))); // NOI18N
        produtobtn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel2.add(produtobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 120, 120));

        cadastrarbtn1.setBackground(new java.awt.Color(247, 249, 249));
        cadastrarbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarbtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarbtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarbtn1MouseExited(evt);
            }
        });
        cadastrarbtn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 255));
        jLabel10.setText("Cadastrar");
        cadastrarbtn1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/registration.png"))); // NOI18N
        cadastrarbtn1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel2.add(cadastrarbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, 120));

        funcionariolist1.setBackground(new java.awt.Color(247, 249, 249));
        funcionariolist1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        funcionariolist1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funcionariolist1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                funcionariolist1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                funcionariolist1MouseExited(evt);
            }
        });
        funcionariolist1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 153, 255));
        jLabel18.setText("Funcionários cadastrados");
        funcionariolist1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/lista_funcionarios.png"))); // NOI18N
        funcionariolist1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel2.add(funcionariolist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 130, 130));

        produtolist.setBackground(new java.awt.Color(247, 249, 249));
        produtolist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        produtolist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtolistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                produtolistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                produtolistMouseExited(evt);
            }
        });
        produtolist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 153, 255));
        jLabel15.setText("Produtos cadastrados");
        produtolist.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/mouse-toy.png"))); // NOI18N
        produtolist.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel2.add(produtolist, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 130, 130));

        servicobtn1.setBackground(new java.awt.Color(247, 249, 249));
        servicobtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        servicobtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicobtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                servicobtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                servicobtn1MouseExited(evt);
            }
        });
        servicobtn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 153, 255));
        jLabel20.setText("Cadastrar Serviço");
        servicobtn1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/pets-hair-salon-tools-kit.png"))); // NOI18N
        servicobtn1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel2.add(servicobtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 130, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void produtobtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtobtnMouseEntered

        produtobtn.setBackground(hover);


    }//GEN-LAST:event_produtobtnMouseEntered

    private void produtobtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtobtnMouseExited
        // TODO add your handling code here:
        produtobtn.setBackground(base);
    }//GEN-LAST:event_produtobtnMouseExited

    private void listaclientebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaclientebtnMouseEntered
        listaclientebtn.setBackground(hover);

    }//GEN-LAST:event_listaclientebtnMouseEntered

    private void petlistbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petlistbtnMouseEntered

        petlistbtn.setBackground(hover);


    }//GEN-LAST:event_petlistbtnMouseEntered

    private void petlistbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petlistbtnMouseExited
        // TODO add your handling code here:

        petlistbtn.setBackground(base);

    }//GEN-LAST:event_petlistbtnMouseExited

    private void listaclientebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaclientebtnMouseExited
        listaclientebtn.setBackground(base);


    }//GEN-LAST:event_listaclientebtnMouseExited

    private void produtobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtobtnMouseClicked

        Cadastro_produto cadastro_produto = new Cadastro_produto();
        this.setVisible(false);
        cadastro_produto.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_produtobtnMouseClicked

    private void funcionariobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariobtnMouseClicked
        // TODO add your handling code here:
        Cadastro_funcionario cf = new Cadastro_funcionario();
        this.setVisible(false);
        cf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_funcionariobtnMouseClicked

    private void funcionariobtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariobtnMouseEntered
        // TODO add your handling code here:
        funcionariobtn.setBackground(hover);
    }//GEN-LAST:event_funcionariobtnMouseEntered

    private void funcionariobtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariobtnMouseExited
        // TODO add your handling code here:
        funcionariobtn.setBackground(base);
    }//GEN-LAST:event_funcionariobtnMouseExited

    private void produtolistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtolistMouseEntered
        // TODO add your handling code here:
        produtolist.setBackground(hover);
    }//GEN-LAST:event_produtolistMouseEntered

    private void produtolistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtolistMouseExited
        // TODO add your handling code here:
        produtolist.setBackground(base);
    }//GEN-LAST:event_produtolistMouseExited

    private void listaclientebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaclientebtnMouseClicked

        try {
            Clientes c = new Clientes();
            this.setVisible(false);
            c.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_listaclientebtnMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered

        Color darkred = new Color(130, 0, 0);

        close.setBackground(darkred);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        Color red = new Color(255, 101, 101);

        close.setBackground(red);
        closelabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_closeMouseExited

    private void produtolistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtolistMouseClicked
        try {
            // TODO add your handling code here:
            view.Produtos f = new view.Produtos();
            this.setVisible(false);
            f.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_produtolistMouseClicked

    private void petlistbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petlistbtnMouseClicked

        try {
            Pets pets = new Pets();
            this.setVisible(false);
            pets.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_petlistbtnMouseClicked

    private void cadastrarbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarbtn1MouseClicked
        // TODO add your handling code here:
        Cadastro_cliente cadastro_cliente = new  Cadastro_cliente();
        this.setVisible(false);
        cadastro_cliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarbtn1MouseClicked

    private void cadastrarbtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarbtn1MouseEntered
        // TODO add your handling code here:
        cadastrarbtn1.setBackground(hover);
    }//GEN-LAST:event_cadastrarbtn1MouseEntered

    private void cadastrarbtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarbtn1MouseExited
        // TODO add your handling code here:
        cadastrarbtn1.setBackground(base);
    }//GEN-LAST:event_cadastrarbtn1MouseExited

    private void servicolistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicolistMouseClicked

        try {
            view.Servicos s = new view.Servicos();
            this.setVisible(false);
            s.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_servicolistMouseClicked

    private void servicolistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicolistMouseEntered
        // TODO add your handling code here:
        servicolist.setBackground(hover);
    }//GEN-LAST:event_servicolistMouseEntered

    private void servicolistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicolistMouseExited
        // TODO add your handling code here:
                servicolist.setBackground(base);

        
    }//GEN-LAST:event_servicolistMouseExited

    private void funcionariolist1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariolist1MouseClicked
        try {
            // TODO add your handling code here:
            Funcionarios f = new Funcionarios();
            this.setVisible(false);
            f.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_funcionariolist1MouseClicked

    private void funcionariolist1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariolist1MouseEntered
        // TODO add your handling code here:
        funcionariolist1.setBackground(hover);
    }//GEN-LAST:event_funcionariolist1MouseEntered

    private void funcionariolist1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariolist1MouseExited
        // TODO add your handling code here:
        funcionariolist1.setBackground(base);
    }//GEN-LAST:event_funcionariolist1MouseExited

    private void servicobtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicobtn1MouseClicked
        // TODO add your handling code here:
        Cadastro_servico cadastro_servico = new Cadastro_servico();
        this.setVisible(false);
        cadastro_servico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_servicobtn1MouseClicked

    private void servicobtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicobtn1MouseEntered
        // TODO add your handling code here:
        servicobtn1.setBackground(hover);
    }//GEN-LAST:event_servicobtn1MouseEntered

    private void servicobtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicobtn1MouseExited
        // TODO add your handling code here:
        servicobtn1.setBackground(base);

    }//GEN-LAST:event_servicobtn1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cadastrarbtn1;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closelabel;
    private javax.swing.JPanel funcionariobtn;
    private javax.swing.JPanel funcionariolist1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel listaclientebtn;
    private javax.swing.JPanel petlistbtn;
    private javax.swing.JPanel produtobtn;
    private javax.swing.JPanel produtolist;
    private javax.swing.JPanel servicobtn1;
    private javax.swing.JPanel servicolist;
    // End of variables declaration//GEN-END:variables
}
